name: sweetalert
description: sweet alert for flutter.
version: 0.0.2
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/jzoom/sweetalert

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sequence_animation: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
